### ISSUE TITLE
Windows container issues

### ISSUE THREAD

**Issue by ebeshero** [djbpitt/collatex-docker#8]
This is a summary of major problems encountered on 2017-12-27 with attempting to run the docker image. 
1) When using the run command, we face issues with the way the git bash shell in windows *and* the windows powershell expects file paths. Each of these expects something a little different. A significant issue is that a literal file path can be "unpacked" into a location in a Git location. This seems to be remedied by using syntax like //c/Users/.../  . 

2) Once we figure out a way around the path mangling, we face a basic problem we haven't yet solved: We fail to execute start-notebook.sh because files inside the container aren't found.  Here is one sample featuring the problem:
```shell
$ winpty docker run -it -p 8888:8888 --rm -v //c/Users/Lisa/Desktop/DockerCollateXTest/work:/home/jovyan/work collatex
[FATAL tini (5)] Executing child process 'start-notebook.sh' failed: 'No such file or directory'
```
The docker logs say:
```
[14:12:05.739][ApiProxy       ][Info   ] Rewrote mount //c/Users/Lisa/Desktop/DockerCollateXTest/work:/home/jovyan/work (volumeDriver=) to /c/Users/Lisa/Desktop/DockerCollateXTest/work:/home/jovyan/work
[14:12:05.747][ApiProxy       ][Info   ] Failed to read proxies/http from snaphshot p9p.MessageRerror{Ename:"No such file or directory"}
[14:12:05.747][ApiProxy       ][Info   ] proxy >> POST /v1.32/containers/create
```

@djbpitt created a docker-compose.yml file to attempt to mount the docker container in a way that bypasses the Windows shells in case that's the problem. This still fails in the same way--we're not reaching into the container.  

I'm pushing docker logs from the afternoon of work since these contain records of how paths are rewritten and what errors occurred.

**Comment by djbpitt** [comment]
The fix required the following:

* Surround the entire `-v` parameter value to `docker run` in single quotation marks.
* Surround all paths in commands inside the `Dockerfile` in single quotation marks.
* Install (`apt-get`) `tofrodos` (a `dos2unix` utility) and run `fromdos` against `start-notebook.sh` after copying it into the container. A trailing `^M` was preventing it from running.
